version: '3'

services:

  client:
    image: frixaco/viconf
    # build: .
    ports:
      - "80:80"
      - "443:443"

  server:
    image: frixaco/viconf-server
    # build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
